# Generated by Django 5.2.16 on 2026-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('provider_song_id', models.CharField(max_length=200)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('artist', models.CharField(db_index=True, max_length=300)),
                ('album', models.CharField(blank=True, max_length=300)),
                ('cover_url', models.URLField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('stream_url', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_song_id'], name='music_song_provide_be38c3_idx'), models.Index(fields=['title'], name='music_song_title_8e56ff_idx'), models.Index(fields=['artist'], name='music_song_artist_173532_idx')],
                'unique_together': {('provider', 'provider_song_id')},
            },
        ),
    ]
